//created on: 04-ago-2015
package rules

import com.sample.modelo.Problema;
import com.sample.modelo.TipoEstado;
import com.sample.modelo.Diagnostico;
import java.util.ArrayList;

global com.sample.modelo.Diagnostico diagnostico
global com.sample.vista.PanelProblemaAudio vista

rule "regla inicial"
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA)
	then
		vista.cambiarElementos();
		
		vista.cambiarSugerencia("Infiriendo");
end

rule "verificacion no escuchamos"
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA) and 
		Problema(estado == TipoEstado.NOS_ESCUCHAN) and 
		Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA)
	then
		vista.cambiarSugerencia("revisar el estado de los componentes pasivos (capacitores, resistencias y bobinas) de la zona de donde se conecta el auricular.");
		vista.mostrarSugerencia();
end

rule "verificacion componentes pasivos"
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA) and 
		Problema(estado == TipoEstado.NOS_ESCUCHAN) and 
		Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA) and
		Problema(estado == TipoEstado.COMPONENTES_PASIVOS_BUEN_ESTADO)
	then
		vista.cambiarSugerencia("realizar un resoldado de las componentes pasivos.");
		vista.mostrarSugerencia();
end

rule "verificar no nos escuchan regla 3"
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA) and 
		(Problema(estado == TipoEstado.NO_NOS_ESCUCHAN) or
		Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA))
	then
		vista.cambiarSugerencia("usar manos libres (audífonos)");
		vista.mostrarSugerencia();
end

rule "verificar no se escucha con audifonos"
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA) and 
		(Problema(estado == TipoEstado.NO_NOS_ESCUCHAN) or
		Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA)) and
		Problema(estado == TipoEstado.NO_SE_ESCUCHA_CON_AUDIFONOS)
	then
		vista.cambiarSugerencia("limpiar el conector inferior ");
		vista.mostrarSugerencia();
end


rule "verificar conectores estan limpios"
	
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA) and 
		(Problema(estado == TipoEstado.NO_NOS_ESCUCHAN) or
		Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA)) and
		Problema(estado == TipoEstado.NO_SE_ESCUCHA_CON_AUDIFONOS) and
		Problema(estado == TipoEstado.CONECTORES_LIMPIOS)
	then
		vista.cambiarSugerencia("resoldar los componentes del AF y Área Lógica");
		vista.mostrarSugerencia();
		
end

rule "verificar microfono"
	// Resolucion de conflicto con la regla 3 (Esta regla se ejecutara primero)
	salience 10
	when
		Problema(estado == TipoEstado.REALIZA_LLAMADA) and 
		Problema(estado == TipoEstado.NO_NOS_ESCUCHAN)
		
	then
		insert(new Problema(TipoEstado.MICROFONO));
end

rule "verificar si escuchamos durante las llamadas"
	when
		Problema(estado == TipoEstado.MICROFONO)
		Problema(estado == TipoEstado.ESCUCHAMOS)
	then
		vista.cambiarSugerencia("Reemplazar el microfono del celular");
		vista.mostrarSugerencia();
end

