//created on: 04-ago-2015
package rules

import com.sample.modelo.Problema;
import com.sample.modelo.TipoEstado;
import com.sample.modelo.Diagnostico;
import java.util.ArrayList;

global com.sample.modelo.Diagnostico diagnostico
//global vista

rule "Verificar que no escuchamos"
	salience 10

	when
		problema : Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA)
	then
		diagnostico.agregarProblema(problema);
		mandarMensajeVista();
		System.out.println("Hola mundo como estan todos");
end


rule "Verificar Componentes Pasivos"
	when
		
		//problema : Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA ||  == TipoEstado.COMPONENTES_PASIVOS_BUEN_ESTADO)
		ArrayList(size == 2) from collect( Problema(estado == TipoEstado.NO_ESCUCHAMOS_NADA ||  == TipoEstado.COMPONENTES_PASIVOS_BUEN_ESTADO) )
	then
		//diagnostico.agregarProblema(problema);
		System.out.println("que macana");
end

rule "verificar que no nos escuchan"
	when
		exists (Problema(estado == TipoEstado.NO_NOS_ESCUCHAN) and Problema(estado == TipoEstado.NO_ESCUCHAN_CON_AUDIFONOS))
	then
		System.out.println("hola");
end

rule "verificar que no se escuchan con audifonos"
	when
		Problema(estado == TipoEstado.NO_ESCUCHAN_CON_AUDIFONOS)
	then
		
end

rule "verificar que los conectores estan limpios"
	when
		exists (Problema(estado == TipoEstado.CONECTORES_LIMPIOS) and Problema(estado == TipoEstado.NO_ESCUCHAN_CON_AUDIFONOS))
	then
		
end

function void mandarMensajeVista() {
	System.out.println("todo bien aqui");
}
