package com.sample
 
import com.sample.DroolsTest.Message;
import com.sample.modelo.Problema;
import com.sample.modelo.TipoEstado;
import com.sample.modelo.Diagnostico;
 

 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end


